[package]
name = "silex-cli"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "silex-cli"
path = "src/main.rs"
required-features = ["cli"]

[[example]]
name = "api_simulation"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["dep:clap", "dep:tokio"]
wasm = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:js-sys"]

[dependencies]
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
indexmap = "2"
log = "0.4"
runtime-context = "0.1"

silex-abi = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-assembler = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-builder = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-bytecode = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-compiler = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-environment = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-lexer = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-parser = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-types = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
silex-decompiler = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
xelis-vm = { git = "https://github.com/xelis-project/xelis-vm", tag = "v1.4.0" }
xelis_common = { git = "https://github.com/xelis-project/xelis-blockchain", branch = "dev" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4", features = ["derive"], optional = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
